### ISSUE TITLE
Feature Request: NBT/JSON Structures for Architecture Crystals

### ISSUE THREAD

**Issue by ALJ323** [Yuzunyannn/ElementalSorcery#1]
Requesting the ability to define structures via JSON or placing NBT files in the config folder that pack makers can use to add Architecture Crystals that build their own structures when tuned to a defined frequency.

**Comment by Yuzunyannn** [comment]
That's a good idea, I will design and add it in my next plan of reconstructing The Structure Part.

**Comment by Yuzunyannn** [comment]
A New Tile Frequency Inductor is added for it, and config can be find on .minecraft/Elemental Sorcery/building/frequency_map.json after starting game with 0.7.0
