### ISSUE TITLE
Crash on title screen Elemental Sorcery 0.17 with Quark

### ISSUE THREAD

**Issue by ALJ323** [Yuzunyannn/ElementalSorcery#11]
https://mclo.gs/1B0kUPP

Will try to narrow down the circumstance over time. Previous 0.16 configs have been refreshed.

**Comment by ALJ323** [comment]
It seems to be incompatible with the Quark mod

**Comment by Yuzunyannn** [comment]
crash beacuse 'minecraft:flower_pot' state.getBlock() is not equal with Blocks.FLOWER_POT.
I guess Quark replaced 'minecraft:flower_pot' in block's registry with another instance which cause this problem.
I need lagging buildings loading to ensure Quark's replacing is completed.
