### ISSUE TITLE
[Crash] Arrogant Sheep Disappearing Gold Block Ticking  (Elemental Sorcery v.0.12.0)

### ISSUE THREAD

**Issue by ALJ323** [Yuzunyannn/ElementalSorcery#7]
Been testing out a couple things again, I can't seem to replicate this one but over time eventually the disappearing/reappearing blocks in the Arrogant Sheep's chamber seems to have a slight chance to lock up and crash the game. See log:
[2022-06-03-4.log](https://github.com/Yuzunyannn/ElementalSorcery/files/8834827/2022-06-03-4.log)

Another thing is a series of other minor errors were occurring every time when the gold zombies attacked me prior to that ticking crash, though this wasn't initially the case, not sure what triggered that behavior. 
Figured I'd report anyway as you fine tune this magnum opus while I try to wrap my head around this neat new reactor you've gifted us with. 
Side Note:
Is there an intended way to be able to jump up to the Arrogant Sheep besides ender pearls? The disappearing blocks seem to also have that jump bonus, but they don't seem to be reachable..

**Comment by Yuzunyannn** [comment]
Thank for your testing.
I find bug with this log. Some Block can random move around in Sheep's chamber, if it have only one position to choose, crash will be caused.
*Drop The Scarlet Crystal on the Block in Sheep's chamber and wait a while, the Block will change to jump bonus block.
