### ISSUE TITLE
Quality of Life: Toggle for chat blurbs

### ISSUE THREAD

**Issue by ALJ323** [Yuzunyannn/ElementalSorcery#9]
I was wondering if there was a way to turn off the chat spam for whatever is triggering the messages stating things along the lines of "Are you interested in [Natural]" when breaking grass and such?

If not, I was wondering if this could be implemented? I am unsure what purpose it serves and I assumed initially it was an elf asking things despite them not being present, or perhaps some sort of debug feature. Could this be explained if this ties into something else where its necessary?

**Comment by Yuzunyannn** [comment]
This is a message telling player about Topic Point is grow, which used to craft some item with Research Square Table in Elf Laboratory.
As you said, it bother player and be confusable. I should think of some other way to explain this.
